### ISSUE TITLE
Стилизовать devise views

### ISSUE THREAD

**Issue by realvint** [rubyfansdev/crm#4]
Нужно переверстать вьюхи devise ( только регистрация и авторизация) под simple-form. Сделать красиво

[дока simple-form](https://github.com/heartcombo/simple_form#usage)

**Comment by o-200** [comment]
> Нужно переверстать вьюхи devise ( только регистрация и авторизация) под simple-form
> 
> [дока simple-form](https://github.com/heartcombo/simple_form#usage)

я бы хотел взять issue

**Comment by realvint** [comment]
Бери. Предложения с большой буквы пишут)

**Comment by o-200** [comment]
> Бери. Предложения с большой буквы пишут)

После того, как я перенес все под simple_form, теперь формы расстягиваются на весь экран. Может стоит перенести форму на середину и ограничить ширину у формы? 

![изображение](https://github.com/rubyfansdev/crm/assets/34093966/8f38a0d9-f3e8-4d58-9b6c-2c7dc83156ba)

**Comment by realvint** [comment]
@o-200 Сделай красиво) С учётом просмотра на мобилках в 320px

**Comment by realvint** [comment]
@o-200 Красиво это примерно вот так вот

![krasivo](https://github.com/rubyfansdev/crm/assets/68920864/cafa2202-4255-47bf-8224-7a8f7a38d804)
