### ISSUE TITLE
Добавить верхнее меню (Navbar)

### ISSUE THREAD

**Issue by realvint** [rubyfansdev/crm#5]
Добавить Bootstrap navbar со ссылками:

-  главная 
-  войти 
- зарегистрироваться
- выйти (если залогинен)

Показать email юзера, если залогинен

Вынести меню в отдельный partal: `shared/_navbar.slim`

**Comment by o-200** [comment]
Привет я бы хотел взять ишью

**Comment by o-200** [comment]
@realvint

**Comment by realvint** [comment]
> Привет я бы хотел взять ишью

ok
